name: publish-to-github-pages

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  depoy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install with npm
        run: npm install
      - name: Build with npm
        run: npm run build
      - name: Cleanup files
        run: |
          ls | grep -v dist | grep -v CNAME | xargs rm -rf
          mv dist/* .
          rm -r dist
      - name: Push to gh-pages branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b gh-pages
          git add .
          git commit -m "Automatically built"
          git push --force --set-upstream origin gh-pages
